/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainServicesRouteImport } from './routes/_main/services'
import { Route as MainContactRouteImport } from './routes/_main/contact'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as MainServicesIndexRouteImport } from './routes/_main/services/index'
import { Route as MainServicesWebdesignRouteImport } from './routes/_main/services/webdesign'
import { Route as MainServicesSeoRouteImport } from './routes/_main/services/seo'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainServicesRoute = MainServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => MainRoute,
} as any)
const MainContactRoute = MainContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MainRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRoute,
} as any)
const MainServicesIndexRoute = MainServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainServicesRoute,
} as any)
const MainServicesWebdesignRoute = MainServicesWebdesignRouteImport.update({
  id: '/webdesign',
  path: '/webdesign',
  getParentRoute: () => MainServicesRoute,
} as any)
const MainServicesSeoRoute = MainServicesSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => MainServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof MainAboutRoute
  '/contact': typeof MainContactRoute
  '/services': typeof MainServicesRouteWithChildren
  '/': typeof MainIndexRoute
  '/services/seo': typeof MainServicesSeoRoute
  '/services/webdesign': typeof MainServicesWebdesignRoute
  '/services/': typeof MainServicesIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof MainAboutRoute
  '/contact': typeof MainContactRoute
  '/': typeof MainIndexRoute
  '/services/seo': typeof MainServicesSeoRoute
  '/services/webdesign': typeof MainServicesWebdesignRoute
  '/services': typeof MainServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/contact': typeof MainContactRoute
  '/_main/services': typeof MainServicesRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/services/seo': typeof MainServicesSeoRoute
  '/_main/services/webdesign': typeof MainServicesWebdesignRoute
  '/_main/services/': typeof MainServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/contact'
    | '/services'
    | '/'
    | '/services/seo'
    | '/services/webdesign'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/'
    | '/services/seo'
    | '/services/webdesign'
    | '/services'
  id:
    | '__root__'
    | '/_main'
    | '/_main/about'
    | '/_main/contact'
    | '/_main/services'
    | '/_main/'
    | '/_main/services/seo'
    | '/_main/services/webdesign'
    | '/_main/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/services': {
      id: '/_main/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof MainServicesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/contact': {
      id: '/_main/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MainContactRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/services/': {
      id: '/_main/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof MainServicesIndexRouteImport
      parentRoute: typeof MainServicesRoute
    }
    '/_main/services/webdesign': {
      id: '/_main/services/webdesign'
      path: '/webdesign'
      fullPath: '/services/webdesign'
      preLoaderRoute: typeof MainServicesWebdesignRouteImport
      parentRoute: typeof MainServicesRoute
    }
    '/_main/services/seo': {
      id: '/_main/services/seo'
      path: '/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof MainServicesSeoRouteImport
      parentRoute: typeof MainServicesRoute
    }
  }
}

interface MainServicesRouteChildren {
  MainServicesSeoRoute: typeof MainServicesSeoRoute
  MainServicesWebdesignRoute: typeof MainServicesWebdesignRoute
  MainServicesIndexRoute: typeof MainServicesIndexRoute
}

const MainServicesRouteChildren: MainServicesRouteChildren = {
  MainServicesSeoRoute: MainServicesSeoRoute,
  MainServicesWebdesignRoute: MainServicesWebdesignRoute,
  MainServicesIndexRoute: MainServicesIndexRoute,
}

const MainServicesRouteWithChildren = MainServicesRoute._addFileChildren(
  MainServicesRouteChildren,
)

interface MainRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainContactRoute: typeof MainContactRoute
  MainServicesRoute: typeof MainServicesRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainContactRoute: MainContactRoute,
  MainServicesRoute: MainServicesRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
